# Site settings
description: 본 블로그는 보안 연구 관련 블로그 입니다. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hajacrew.github.io" # the base hostname & protocol for your site 

# User settings
username: HAJACREW
user_description: Security Researcher At NURILAB
user_title: Security Researcher
email: mptstory@gmail.com
github_username: hajacrew
disqus_username: hajacrew

# Build settings
markdown: kramdown
highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Security
    url: /Security
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
